### ISSUE TITLE
Properly incorporate PTIB

### ISSUE THREAD

**Issue by lindsay-fredrick** [bcgov/post-secondary-supply-model#34]
Right now PTIB is not fully incorporated into the model - need to investigate whether the method is correct, and if so implement into main workflow.

**Comment by aclowery** [comment]
Noting we have confirmed that PTIB is not included in the main model, and we have confirmed the incorporation as a separate run. Should we close this issue?

**Comment by lindsay-fredrick** [comment]
Yes!
